{"uuid": "9315f92e-871c-496f-8442-b65ca708db2c", "children": ["7e79e315-677d-4ac7-9d07-0fecf7bdd265"], "befores": [{"name": "_UnitTestCase__pytest_class_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): 'noReset' must be of type boolean\n\n", "trace": "  File \"C:\\Users\\xuan\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\xuan\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\xuan\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\xuan\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\unittest.py\", line 131, in fixture\n    setup()\n  File \"E:\\heimaSoftTest\\Python_ClassCode\\UI_day11_hmtt_ui_test01\\case\\app\\test_query_aritcal.py\", line 13, in setUpClass\n    cls.driver = DriverUtils.get_app_driver()\n  File \"E:\\heimaSoftTest\\Python_ClassCode\\UI_day11_hmtt_ui_test01\\utils.py\", line 94, in get_app_driver\n    cls.__app_driver = appium.webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)\n  File \"C:\\Users\\xuan\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 155, in __init__\n    proxy\n  File \"C:\\Users\\xuan\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\xuan\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"C:\\Users\\xuan\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\xuan\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1598510882047, "stop": 1598510884116}], "start": 1598510882047, "stop": 1598510884446}